services:
  - type: web
    name: securelens
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python setup_nltk.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 180 --log-level debug --max-requests 1000 --max-requests-jitter 50 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: true
      - key: PYTHONUNBUFFERED
        value: true
      - key: WEB_CONCURRENCY
        value: 1
    autoDeploy: false
    healthCheckPath: /
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 0.5
