services:
  - type: web
    name: securelens
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python setup_nltk.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 600 --keep-alive 10 --max-requests 100 --preload --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: PYTHONUNBUFFERED
        value: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONPATH
        value: .
    autoDeploy: false
    healthCheckPath: /health
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 0.5
