services:
  - type: web
    name: securelens
    env: python
    plan: free
    buildCommand: |
      # Upgrade pip and install dependencies
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      
      # Download NLTK data
      python setup_nltk.py
      
      # Create cache directories for models
      mkdir -p ~/.cache/torch/hub/
      mkdir -p ~/.cache/huggingface/
      
      # Pre-download models during build
      python -c "from transformers import AutoTokenizer; AutoTokenizer.from_pretrained('bert-base-uncased')"
      
      # Verify installations
      python -c "import nltk; import torch; import transformers; print('✅ All dependencies installed')"
    startCommand: |
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 \
        --threads 4 \
        --timeout 180 \
        --keep-alive 5 \
        --max-requests 1200 \
        --max-requests-jitter 100 \
        --preload \
        --access-logfile - \
        --error-logfile - \
        --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: MONGO_URI
        fromSecret: MONGO_URI
      - key: DEBUG
        value: false
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FLASK_ENV
        value: production
